[package]
name = "win32"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "quake2"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
